### ISSUE TITLE
Archive repo

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/ServicesDocumentation#13]
- [x] Archive staging branch #14
- [x] Archive master branch #15
- [x] Archive TR_SiGLServicesDocumentation branch #17 
- [x] Archive TR_STNServicesDocumentation branch #16 
- [x] Edit repo settings to set archive status
